@HostAddress = http://localhost:5236

GET {{HostAddress}}/pets/mizzy
Accept: application/json

###

GET {{HostAddress}}/pets/mizzy2
Accept: application/json

###

GET {{HostAddress}}/pets/mizzy3
Accept: application/json

###

GET {{HostAddress}}/pets/fido
Accept: application/json

###

GET {{HostAddress}}/pets/lassie
Accept: application/json

###

GET {{HostAddress}}/pets/snoopy
Accept: application/json

###