@HostAddress = http://localhost:5054

GET {{HostAddress}}/Test
Accept: application/json

###

GET {{HostAddress}}/Test2
Accept: application/json

###

POST {{HostAddress}}/Test2
Accept: application/json
Content-Type: application/json

{
  "x": "Test"
}

###

POST {{HostAddress}}/Test2
Accept: application/json

###

PUT {{HostAddress}}/Test2
Accept: application/json

###

GET {{HostAddress}}/Test3
Accept: application/json

###